### ISSUE TITLE
Not working with CLOZE questions

### ISSUE THREAD

**Issue by malone01** [maths/moodle-qbank_importasversion#2]
Hello,
when trying to import questions of type CLOZE I get the error message: 
**Coding error detected, it must be fixed by a programmer: Invalid context id specified context::instance_by_id()**
Please can you provide a quick fix - I have to update a lot of questions until next week.
Thank you
Martin

**Comment by malone01** [comment]
What I have forgotten before: attached you find a screenshot of the error message incl. debugging details 
[Import-as-version_Coding-error.pdf](https://github.com/maths/moodle-qbank_importasversion/files/14774567/Import-as-version_Coding-error.pdf)

**Comment by malone01** [comment]
For details you find the screenshot attached (incl. debugging details)
![Import-as-version_Coding-error](https://github.com/maths/moodle-qbank_importasversion/assets/107833732/076d788c-c576-4ac0-b320-d2c2704cfc19)

**Comment by timhunt** [comment]
Ideally, we would add a PHPunit test to reproduce the bug, then fix it. If that fix works, it is not obvious to me why, but I have not thought about it very hard.

**Comment by malone01** [comment]
From Andreas Steiger I got the following fix (many thanks to Andreas):

> In `question/bank/importasversion/classes/importer.php', add new line 91:
>         $newquestion->category = $question->category;
> Afterwards lines 90-92 are:
>         $newquestion->context = $context; // Context is taken from the existing question.
>         $newquestion->category = $question->category;
>         $newquestion->id = $DB->insert_record('question', $importedquestion);

This solved my problem and the import of "cloze" questions as new version works as expected. 

Best regards
Martin

**Comment by timhunt** [comment]
OK. Seems this is solved. Marking closed.
